[package]
name = "oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
oxide-core = { path = "../oxide-core" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3.18"
