[award]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[admin]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[ban]
create = "judge"
update = "moderator"
delete = "analyst"
read = "analyst"

[challenge_tag]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[challenge]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[container]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[deployment]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[file]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[flag]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[hint]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[instance]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[invite]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[notification]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[player]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[submission]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[tag]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[team]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[ticket]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[unlock]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"

[user]
create = "analyst"
update = "analyst"
delete = "analyst"
read = "analyst"
