[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[workspace.dependencies]
axum = { version = "0.7.7", features = ["macros", "multipart"] }
chrono = { version = "0.4.38", features = ["serde"] }
sea-orm = { version = "1.0.1", features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tracing = "0.1.40"
utoipa = { version = "4.2.3", features = [
    "axum_extras",
    "uuid",
    "chrono",
    "url",
] }
