[ctf]
name = "Athena CTF"
duration = "2days"
start_time = "2024-08-18T15:02:06.123250700Z"
freeze_duration = "1day"
domain_name = "athena.io"
description = "Athena is a hosted platform for CTFs"

[database]
host = "postgres"
port = 5432
username = "postgres"
password = "XRXEBROZGpOP"

[redis.cache]
host = "redis_cache"
port = 6379
username = "redis_cache"
password = "tf90blSAad3I"

[redis.token]
host = "redis_token"
port = 6380
username = "redis_token"
password = "Wf9YblSjLd3I"

[file_storage.static_server]
compress = "gzip"
path = "/var/athena/static"

[jwt]
secret = "39vAUPa1rlYcDQIhrh5hfb2YJ4tnZB0VhujDi1jJM+c="
access_token_timeout = 600
refresh_token_timeout = 86400

[smtp]
from = "noreply@athena.io"
reply_to = "Admin <admin@athena.io>"
username = "athena_smtp"
password = "zOvGBoAcm5Uc"
server_url = "smtp.athena.io"

[docker]
single_instance_duration = 15
registry_url = "registry.athena.io"
registry_username = "athena"
registry_password = "I5DSnxhA71bI"

[discord]
welcome_channel_id = ""
editor_role_id = ""
viewer_role_id = ""
reaction_role_message_id = ""
logs_channel_id = ""
genral_channel_id = ""rgo
