[ctf]
name = "Athena CTF"
domain = "athena.io"
description = "Athena is a hosted platform for CTFs"
challenge = { max_attempts = 10 }
sponsors = {}
prizes = {}

[ctf.time]
span = "2days"
start = "2024-10-13T11:31:36.949912752Z"
freeze = "1day"

[database]
host = "postgres"
port = 5432
username = "postgres"
password = "9U5HmF8SjDW5"

[redis.cache]
host = "redis"
port = 6379
username = "redis_cache"
password = "FUTAUAwUmzKc"

[redis.token]
host = "redis"
port = 6379
username = "redis_token"
password = "GKQjmoAqOYxd"

[file_storage]
compress = "gzip"
path = "/var/athena/static"

[jwt]
secret = "6uiainM6/yGGmZHXi7tSirazwutIiZkSGqAuokKmt1E="
access_token_timeout = 600
refresh_token_timeout = 86400

[smtp]
from = "noreply@athena.io"
reply_to = "Admin <admin@athena.io>"
username = "athena_smtp"
password = "7fwO53K8oF7v"
server_url = "smtp.athena.io"

[docker]
single_instance_duration = 15
registry_url = "registry.athena.io"
registry_username = "athena"
registry_password = "O4h9RBYzVKrP"

[discord]
welcome_channel_id = ""
editor_role_id = ""
viewer_role_id = ""
reaction_role_message_id = ""
logs_channel_id = ""
genral_channel_id = ""
bot_token = ""
