[team]
create = 0
update = 0
delete = 0
list = 0
retrieve = 0
retrieve_invite = 0
retrieve_player = 0
calculate_points = 0
list_achievements = 0

[challenge]
retrieve = 0
create = 0
delete = 0
update = 0
list = 0
retrieve_file = 0
retrieve_hint = 0
retrieve_instance = 0
retrieve_tag = 0
calculate_solves = 0
retrieve_relations = 0
list_achievements = 0

[file]
create = 0
retrieve = 0
update = 0
delete = 0
list = 0
retrieve_challenge = 0
upload = 0
download = 0

[hint]
create = 0
retrieve = 0
update = 0
delete = 0
list = 0
retrieve_challenge = 0

[instance]
create = 0
retrieve = 0
update = 0
list = 0
delete = 0
retrieve_player = 0
retrieve_challenge = 0

[notification]
create = 0
retrieve = 0
update = 0
delete = 0
list = 0
retrieve_player = 0

[submission]
create = 0
retrieve = 0
update = 0
delete = 0
list = 0
retrieve_player = 0

[flag]
create = 0
update = 0
delete = 0
verify = 0
list = 0
retrieve = 0
retrieve_player = 0
retrieve_challenge = 0

[invite]
retrieve = 0
create = 0
update = 0
delete = 0
list = 0
retrieve_team = 0
join_team = 0

[ban]
create = 0
update = 0
retrieve = 0
list = 0
delete = 0
retrieve_player = 0
retrieve_team = 0
ban_player = 0
ban_team = 0

[tag]
create = 0
update = 0
retrieve = 0
delete = 0
list = 0
retrieve_challenge = 0

[player]
create = 0
update = 0
list = 0
delete = 0
retrieve = 0
update_profile = 0
retrieve_flag = 0
retrieve_submission = 0
retrieve_team = 0
list_achievements = 0
retrieve_instance = 0
calculate_points = 0
rankings = 0

[achievement]
list = 0
retrieve = 0
update = 0
create = 0
delete = 0
retrieve_challenge = 0
retrieve_player = 0
retrieve_team = 0

[stat]
get = 0
