[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }
oxide-macros = { path = "../oxide-macros" }

[build-dependencies]
utoipa-config = "0.1.2"
