[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }
oxide-macros = { path = "../oxide-macros" }
