[package]
name = "migration"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { workspace = true }
sea-orm-migration = { version = "1.1.2", features = [
    "runtime-tokio",
    "sqlx-postgres",
    "with-chrono",
    "with-json",
    "with-uuid",
] }
tokio = { workspace = true }
